id: jbossdemocentral-brms-rating
title: JBoss BRMS Rating Demo
github_repo_url: https://github.com/jbossdemocentral/brms-rating-demo
technologies:
  - JBoss EAP
  - JBoss BRMS
summary: Project to automate the installation of this product without preconfiguration beyond a single admin user. There are three options available to you for using this demo; local, OpenShift and containerized.
level: Beginner
product: brms
author: Andrew Block, Eric D. Schabell, Duncan Doyle, Jaen Swart
